module.exports = function(grunt) {
    require('jit-grunt')(grunt);

    grunt.initConfig({
        less: {
            development: {
                options: {
                    compress: true,
                    yuicompress: true,
                    optimization: 2
                },
                files: {
                    'assets/css/bdt-uikit.css'                    : 'assets/less/bdt-uikit.less',
                    'assets/css/ep-helper.css'                    : 'assets/less/helper.less',
                    'assets/css/ep-editor.css'                    : 'assets/less/editor.less',
                    'assets/css/ep-preview.css'                   : 'assets/less/preview.less',
                    'assets/css/ep-accordion.css'                 : 'assets/less/widgets/accordion.less',
                    'assets/css/ep-comparison-list.css'                 : 'assets/less/widgets/comparison-list.less',
                    'assets/css/ep-advanced-button.css'           : 'assets/less/widgets/advanced-button.less',
                    'assets/css/ep-advanced-counter.css'          : 'assets/less/widgets/advanced-counter.less',
                    'assets/css/ep-advanced-divider.css'          : 'assets/less/widgets/advanced-divider.less',
                    'assets/css/ep-advanced-heading.css'          : 'assets/less/widgets/advanced-heading.less',
                    'assets/css/ep-advanced-icon-box.css'         : 'assets/less/widgets/advanced-icon-box.less',
                    'assets/css/ep-advanced-image-gallery.css'    : 'assets/less/widgets/advanced-image-gallery.less',
                    'assets/css/ep-advanced-gmap.css'             : 'assets/less/widgets/advanced-gmap.less',
                    'assets/css/ep-advanced-progress-bar.css'     : 'assets/less/widgets/advanced-progress-bar.less',
                    'assets/css/ep-animated-heading.css'          : 'assets/less/widgets/animated-heading.less',
                    'assets/css/ep-audio-player.css'              : 'assets/less/widgets/audio-player.less',
                    'assets/css/ep-booked-calendar.css'           : 'assets/less/widgets/booked-calendar.less',
                    'assets/css/ep-business-hours.css'            : 'assets/less/widgets/business-hours.less',
                    'assets/css/ep-call-out.css'                  : 'assets/less/widgets/call-out.less',
                    'assets/css/ep-carousel.css'                  : 'assets/less/widgets/carousel.less',
                    'assets/css/ep-changelog.css'                 : 'assets/less/widgets/changelog.less',
                    'assets/css/ep-circle-menu.css'               : 'assets/less/widgets/circle-menu.less',
                    'assets/css/ep-contact-form.css'              : 'assets/less/widgets/contact-form.less',
                    'assets/css/ep-cookie-consent.css'            : 'assets/less/widgets/cookie-consent.less',
                    'assets/css/ep-countdown.css'                 : 'assets/less/widgets/countdown.less',
                    'assets/css/ep-crypto-currency-card.css'      : 'assets/less/widgets/crypto-currency-card.less',
                    'assets/css/ep-crypto-currency-table.css'     : 'assets/less/widgets/crypto-currency-table.less',
                    'assets/css/ep-crypto-currency-grid.css'      : 'assets/less/widgets/crypto-currency-grid.less',
                    'assets/css/ep-crypto-currency-ticker.css'    : 'assets/less/widgets/crypto-currency-ticker.less',
                    'assets/css/ep-crypto-currency-chart.css'     : 'assets/less/widgets/crypto-currency-chart.less',
                    'assets/css/ep-crypto-currency-chart-carousel.css' : 'assets/less/widgets/crypto-currency-chart-carousel.less',
                    'assets/css/ep-crypto-currency-list.css'      : 'assets/less/widgets/crypto-currency-list.less',
                    'assets/css/ep-crypto-currency-carousel.css'  : 'assets/less/widgets/crypto-currency-carousel.less',
                    'assets/css/ep-icon-mobile-menu.css'          : 'assets/less/widgets/icon-mobile-menu.less',
                    'assets/css/ep-custom-carousel.css'           : 'assets/less/widgets/custom-carousel.less',
                    'assets/css/ep-circle-info.css'               : 'assets/less/widgets/circle-info.less',
                    'assets/css/ep-custom-gallery.css'            : 'assets/less/widgets/custom-gallery.less',
                    'assets/css/ep-dark-mode.css'                 : 'assets/less/widgets/dark-mode.less',
                    'assets/css/ep-device-slider.css'             : 'assets/less/widgets/device-slider.less',
                    'assets/css/ep-dual-button.css'               : 'assets/less/widgets/dual-button.less',
                    'assets/css/ep-dynamic-grid.css'              : 'assets/less/widgets/dynamic-grid.less',
                    'assets/css/ep-dynamic-carousel.css'          : 'assets/less/widgets/dynamic-carousel.less',
                    /**
                     * since v6.1.14
                     */
                    'assets/css/ep-edd-category-grid.css'         : 'assets/less/widgets/edd-category-grid.less',
                    'assets/css/ep-edd-product.css'               : 'assets/less/widgets/edd-product.less',
                    'assets/css/ep-edd-category-carousel.css'     : 'assets/less/widgets/edd-category-carousel.less',
                    'assets/css/ep-edd-product-carousel.css'      : 'assets/less/widgets/edd-product-carousel.less',
                    'assets/css/ep-edd-tabs.css'                  : 'assets/less/widgets/edd-tabs.less',
                    'assets/css/ep-edd-cart.css'                  : 'assets/less/widgets/edd-cart.less',
                    'assets/css/ep-edd-checkout.css'              : 'assets/less/widgets/edd-checkout.less',

                    /**
                     * since v6.7.XX
                     */
                    'assets/css/ep-edd-mini-cart.css'             : 'assets/less/widgets/edd-mini-cart.less',
                    'assets/css/ep-edd-product-reviews.css'       : 'assets/less/widgets/edd-product-reviews.less',
                    'assets/css/ep-edd-product-review-carousel.css': 'assets/less/widgets/edd-product-review-carousel.less',


                    'assets/css/ep-fancy-list.css'                : 'assets/less/widgets/fancy-list.less',
                    'assets/css/ep-fancy-card.css'                : 'assets/less/widgets/fancy-card.less',
                    'assets/css/ep-fancy-icons.css'               : 'assets/less/widgets/fancy-icons.less',
                    'assets/css/ep-fancy-slider.css'              : 'assets/less/widgets/fancy-slider.less',
                    'assets/css/ep-fancy-tabs.css'                : 'assets/less/widgets/fancy-tabs.less',
                    'assets/css/ep-interactive-tabs.css'          : 'assets/less/widgets/interactive-tabs.less',
                    'assets/css/ep-faq.css'                       : 'assets/less/widgets/faq.less',
                    'assets/css/ep-flip-box.css'                  : 'assets/less/widgets/flip-box.less',
                    'assets/css/ep-helpdesk.css'                  : 'assets/less/widgets/helpdesk.less',
                    'assets/css/ep-hover-box.css'                 : 'assets/less/widgets/hover-box.less',
                    'assets/css/ep-iconnav.css'                   : 'assets/less/widgets/iconnav.less',
                    'assets/css/ep-instagram.css'                 : 'assets/less/widgets/instagram.less',
                    'assets/css/ep-image-parallax.css'            : 'assets/less/widgets/image-parallax.less',
                    'assets/css/ep-lightbox.css'                  : 'assets/less/widgets/lightbox.less',
                    'assets/css/ep-lottie-icon-box.css'           : 'assets/less/widgets/lottie-icon-box.less',
                    'assets/css/ep-logo-grid.css'                 : 'assets/less/widgets/logo-grid.less',
                    'assets/css/ep-logo-carousel.css'             : 'assets/less/widgets/logo-carousel.less',
                    'assets/css/ep-marker.css'                    : 'assets/less/widgets/marker.less',
                    'assets/css/ep-member.css'                    : 'assets/less/widgets/member.less',
                    'assets/css/ep-navbar.css'                    : 'assets/less/widgets/navbar.less',
                    'assets/css/ep-news-ticker.css'               : 'assets/less/widgets/news-ticker.less',
                    'assets/css/ep-offcanvas.css'                 : 'assets/less/widgets/offcanvas.less',
                    'assets/css/ep-open-street-map.css'           : 'assets/less/widgets/open-street-map.less',
                    'assets/css/ep-panel-slider.css'              : 'assets/less/widgets/panel-slider.less',
                    'assets/css/ep-portfolio-gallery.css'         : 'assets/less/widgets/portfolio-gallery.less',
                    'assets/css/ep-portfolio-list.css'            : 'assets/less/widgets/portfolio-list.less',
                    'assets/css/ep-portfolio-carousel.css'        : 'assets/less/widgets/portfolio-carousel.less',
                    'assets/css/ep-post-block-modern.css'         : 'assets/less/widgets/post-block-modern.less',
                    'assets/css/ep-post-block.css'                : 'assets/less/widgets/post-block.less',
                    'assets/css/ep-post-card.css'                 : 'assets/less/widgets/post-card.less',
                    'assets/css/ep-post-gallery.css'              : 'assets/less/widgets/post-gallery.less',
                    'assets/css/ep-post-grid-tab.css'             : 'assets/less/widgets/post-grid-tab.less',
                    'assets/css/ep-post-grid.css'                 : 'assets/less/widgets/post-grid.less',
                    'assets/css/ep-post-list.css'                 : 'assets/less/widgets/post-list.less',
                    'assets/css/ep-post-slider.css'               : 'assets/less/widgets/post-slider.less',
                    'assets/css/ep-price-list.css'                : 'assets/less/widgets/price-list.less',
                    'assets/css/ep-price-table.css'               : 'assets/less/widgets/price-table.less',
                    'assets/css/ep-profile-card.css'              : 'assets/less/widgets/profile-card.less',
                    'assets/css/ep-progress-pie.css'              : 'assets/less/widgets/progress-pie.less',
                    'assets/css/ep-qrcode.css'                    : 'assets/less/widgets/qrcode.less',
                    'assets/css/ep-barcode.css'                   : 'assets/less/widgets/barcode.less',
                    'assets/css/ep-svg-blob.css'                  : 'assets/less/widgets/svg-blob.less',
                    'assets/css/ep-marquee.css'                   : 'assets/less/widgets/marquee.less',
                    'assets/css/ep-mega-menu.css'                 : 'assets/less/widgets/mega-menu.less',
                    'assets/css/ep-sub-menu.css'                  : 'assets/less/widgets/sub-menu.less',
                    'assets/css/ep-scroll-button.css'             : 'assets/less/widgets/scroll-button.less',
                    'assets/css/ep-scroll-image.css'              : 'assets/less/widgets/scroll-image.less',
                    'assets/css/ep-scrollnav.css'                 : 'assets/less/widgets/scrollnav.less',
                    'assets/css/ep-search.css'                    : 'assets/less/widgets/search.less',
                    'assets/css/ep-single-post.css'               : 'assets/less/widgets/single-post.less',
                    'assets/css/ep-slider.css'                    : 'assets/less/widgets/slider.less',
                    'assets/css/ep-slideshow.css'                 : 'assets/less/widgets/slideshow.less',
                    'assets/css/ep-social-share.css'              : 'assets/less/widgets/social-share.less',
                    'assets/css/ep-social-proof.css'              : 'assets/less/widgets/social-proof.less',
                    'assets/css/ep-switcher.css'                  : 'assets/less/widgets/switcher.less',
                    'assets/css/ep-content-switcher.css'          : 'assets/less/widgets/content-switcher.less',
                    'assets/css/ep-table-of-content.css'          : 'assets/less/widgets/table-of-content.less',
                    'assets/css/ep-table.css'                     : 'assets/less/widgets/table.less',
                    'assets/css/ep-tabs.css'                      : 'assets/less/widgets/tabs.less',
                    'assets/css/ep-testimonial-carousel.css'      : 'assets/less/widgets/testimonial-carousel.less',
                    'assets/css/ep-testimonial-grid.css'          : 'assets/less/widgets/testimonial-grid.less',
                    'assets/css/ep-testimonial-slider.css'        : 'assets/less/widgets/testimonial-slider.less',
                    'assets/css/ep-threesixty-product-viewer.css' : 'assets/less/widgets/threesixty-product-viewer.less',
                    'assets/css/ep-thumb-gallery.css'             : 'assets/less/widgets/thumb-gallery.less',
                    'assets/css/ep-timeline.css'                  : 'assets/less/widgets/timeline.less',
                    'assets/css/ep-toggle.css'                    : 'assets/less/widgets/toggle.less',
                    'assets/css/ep-trailer-box.css'               : 'assets/less/widgets/trailer-box.less',
                    'assets/css/ep-twitter-carousel.css'          : 'assets/less/widgets/twitter-carousel.less',
                    'assets/css/ep-twitter-grid.css'              : 'assets/less/widgets/twitter-grid.less',
                    'assets/css/ep-twitter-slider.css'            : 'assets/less/widgets/twitter-slider.less',
                    'assets/css/ep-tutor-lms.css'                 : 'assets/less/widgets/tutor-lms.less',
                    'assets/css/ep-learnpress-grid.css'          : 'assets/less/widgets/learnpress-grid.less',
                    'assets/css/ep-learnpress-carousel.css'      : 'assets/less/widgets/learnpress-carousel.less',
                    'assets/css/ep-time-zone.css'                 : 'assets/less/widgets/time-zone.less',
                    'assets/css/ep-total-count.css'               : 'assets/less/widgets/total-count.less',
                    'assets/css/ep-user-login.css'                : 'assets/less/widgets/user-login.less',
                    'assets/css/ep-user-register.css'             : 'assets/less/widgets/user-register.less',
                    'assets/css/ep-vertical-menu.css'             : 'assets/less/widgets/vertical-menu.less',
                    'assets/css/ep-slinky-vertical-menu.css'      : 'assets/less/widgets/slinky-vertical-menu.less',
                    'assets/css/ep-video-gallery.css'             : 'assets/less/widgets/video-gallery.less',
                    'assets/css/ep-video-player.css'              : 'assets/less/widgets/video-player.less',
                    'assets/css/ep-weather.css'                   : 'assets/less/widgets/weather.less',
                    'assets/css/ep-webhook-form.css'               : 'assets/less/widgets/webhook-form.less',
                    'assets/css/ep-reading-progress.css'          : 'assets/less/widgets/reading-progress.less',
                    'assets/css/ep-google-reviews.css'            : 'assets/less/widgets/google-reviews.less',
                    'assets/css/ep-honeycombs.css'                : 'assets/less/widgets/honeycombs.less',
                    'assets/css/ep-step-flow.css'                 : 'assets/less/widgets/step-flow.less',
                    'assets/css/ep-featured-box.css'              : 'assets/less/widgets/featured-box.less',
                    'assets/css/ep-image-compare.css'             : 'assets/less/widgets/image-compare.less',
                    'assets/css/ep-interactive-card.css'          : 'assets/less/widgets/interactive-card.less',
                    'assets/css/ep-svg-maps.css'                  : 'assets/less/widgets/svg-maps.less',
                    'assets/css/ep-image-accordion.css'           : 'assets/less/widgets/image-accordion.less',
                    'assets/css/ep-image-expand.css'              : 'assets/less/widgets/image-expand.less',
                    'assets/css/ep-iframe.css'                    : 'assets/less/widgets/iframe.less',
                    'assets/css/ep-hover-video.css'               : 'assets/less/widgets/hover-video.less',
                    'assets/css/ep-notification.css'              : 'assets/less/widgets/notification.less',
                    'assets/css/ep-tags-cloud.css'                : 'assets/less/widgets/tags-cloud.less',
                    'assets/css/ep-breadcrumbs.css'               : 'assets/less/widgets/breadcrumbs.less',
                    'assets/css/ep-coupon-code.css'               : 'assets/less/widgets/coupon-code.less',
                    'assets/css/ep-advanced-calculator.css'       : 'assets/less/widgets/advanced-calculator.less',
                    'assets/css/ep-animated-card.css'             : 'assets/less/widgets/animated-card.less',
                    'assets/css/ep-animated-link.css'             : 'assets/less/widgets/animated-link.less',
                    'assets/css/ep-review-card.css'               : 'assets/less/widgets/review-card.less',
                    'assets/css/ep-review-card-grid.css'          : 'assets/less/widgets/review-card-grid.less',
                    'assets/css/ep-review-card-carousel.css'      : 'assets/less/widgets/review-card-carousel.less',
                    'assets/css/ep-static-carousel.css'           : 'assets/less/widgets/static-carousel.less',
                    'assets/css/ep-image-stack.css'               : 'assets/less/widgets/image-stack.less',
                    'assets/css/ep-brand-grid.css'                : 'assets/less/widgets/brand-grid.less',
                    'assets/css/ep-brand-carousel.css'            : 'assets/less/widgets/brand-carousel.less',
                    'assets/css/ep-creative-button.css'           : 'assets/less/widgets/creative-button.less',
                    'assets/css/ep-static-grid-tab.css'           : 'assets/less/widgets/static-grid-tab.less',
                    'assets/css/ep-horizontal-scroller.css'       : 'assets/less/widgets/horizontal-scroller.less',
                    'assets/css/ep-stacker.css'                   : 'assets/less/widgets/stacker.less',
                    'assets/css/ep-events-calendar-grid.css'      : 'assets/less/widgets/events-calendar-grid.less',
                    'assets/css/ep-events-calendar-carousel.css'  : 'assets/less/widgets/events-calendar-carousel.less',
                    'assets/css/ep-events-calendar-list.css'      : 'assets/less/widgets/events-calendar-list.less',
                    'assets/css/ep-wc-add-to-cart.css'            : 'assets/less/widgets/wc-add-to-cart.less',
                    'assets/css/ep-wc-carousel.css'               : 'assets/less/widgets/wc-carousel.less',
                    'assets/css/ep-wc-categories.css'             : 'assets/less/widgets/wc-categories.less',
                    'assets/css/ep-wc-elements.css'               : 'assets/less/widgets/wc-elements.less',
                    'assets/css/ep-wc-mini-cart.css'              : 'assets/less/widgets/wc-mini-cart.less',
                    'assets/css/ep-wc-products.css'               : 'assets/less/widgets/wc-products.less',
                    'assets/css/ep-wc-slider.css'                 : 'assets/less/widgets/wc-slider.less',
                    'assets/css/ep-charitable-campaigns.css'      : 'assets/less/widgets/charitable-campaigns.less',
                    'assets/css/ep-charitable-donation-form.css'  : 'assets/less/widgets/charitable-donation-form.less',
                    'assets/css/ep-charitable-donations.css'      : 'assets/less/widgets/charitable-donations.less',
                    'assets/css/ep-charitable-donors.css'         : 'assets/less/widgets/charitable-donors.less',
                    'assets/css/ep-charitable-login.css'          : 'assets/less/widgets/charitable-login.less',
                    'assets/css/ep-charitable-profile.css'        : 'assets/less/widgets/charitable-profile.less',
                    'assets/css/ep-charitable-registration.css'   : 'assets/less/widgets/charitable-registration.less',
                    'assets/css/ep-charitable-stat.css'           : 'assets/less/widgets/charitable-stat.less',
                    'assets/css/ep-give-donation-history.css'     : 'assets/less/widgets/give-donation-history.less',
                    'assets/css/ep-give-donor-wall.css'           : 'assets/less/widgets/give-donor-wall.less',
                    'assets/css/ep-give-form.css'                 : 'assets/less/widgets/give-form.less',
                    'assets/css/ep-give-form-grid.css'            : 'assets/less/widgets/give-form-grid.less',
                    'assets/css/ep-give-goal.css'                 : 'assets/less/widgets/give-goal.less',
                    'assets/css/ep-give-login.css'                : 'assets/less/widgets/give-login.less',
                    'assets/css/ep-give-profile-editor.css'       : 'assets/less/widgets/give-profile-editor.less',
                    'assets/css/ep-give-receipt.css'              : 'assets/less/widgets/give-receipt.less',
                    'assets/css/ep-give-register.css'             : 'assets/less/widgets/give-register.less',
                    'assets/css/ep-remote-arrows.css'             : 'assets/less/widgets/remote-arrows.less',
                    'assets/css/ep-remote-thumbs.css'             : 'assets/less/widgets/remote-thumbs.less',
                    'assets/css/ep-remote-pagination.css'         : 'assets/less/widgets/remote-pagination.less',
                    'assets/css/ep-remote-fraction.css'           : 'assets/less/widgets/remote-fraction.less',
                    'assets/css/ep-product-grid.css'              : 'assets/less/widgets/product-grid.less',
                    'assets/css/ep-product-carousel.css'          : 'assets/less/widgets/product-carousel.less',
                    'assets/css/ep-facebook-feed.css'             : 'assets/less/widgets/facebook-feed.less',
                    'assets/css/ep-facebook-feed-carousel.css'    : 'assets/less/widgets/facebook-feed-carousel.less',
                    'assets/css/ep-floating-knowledgebase.css'    : 'assets/less/widgets/floating-knowledgebase.less',

                    // third `pa`rty widget less to css
                    'assets/css/jquery-mThumbnailScroller.css'    : 'assets/less/third-party-widgets/jquery-mThumbnailScroller.less',
                    'assets/css/ep-download-monitor.css'          : 'assets/less/third-party-widgets/download-monitor.less',
                    'assets/css/ep-fluent-forms.css'              : 'assets/less/third-party-widgets/fluent-forms.less',
                    'assets/css/ep-everest-forms.css'             : 'assets/less/third-party-widgets/everest-forms.less',
                    'assets/css/ep-mailchimp.css'                 : 'assets/less/third-party-widgets/mailchimp.less',
                    'assets/css/ep-formidable-forms.css'          : 'assets/less/third-party-widgets/formidable-forms.less',
                    'assets/css/ep-forminator-forms.css'          : 'assets/less/third-party-widgets/forminator-forms.less',
                    'assets/css/ep-gravity-forms.css'             : 'assets/less/third-party-widgets/gravity-forms.less',
                    'assets/css/ep-the-newsletter.css'            : 'assets/less/third-party-widgets/the-newsletter.less',
                    'assets/css/datatables.css'                   : 'assets/less/third-party-widgets/datatables.less',
                    'assets/css/datatables-uikit.css'             : 'assets/less/third-party-widgets/datatables.uikit.less',
                    'assets/css/imagezoom.css'                    : 'assets/less/third-party-widgets/imagezoom.less',
                    'assets/css/ep-font.css'                      : 'assets/less/font.less',
                    'assets/css/ep-woocommerce.css'               : 'assets/less/third-party-widgets/woocommerce.less',

                    // Vendor styles
                    'assets/css/tippy.css'                        : 'assets/less/extensions/tippy.less',
                    'assets/vendor/css/prism.css'                 : 'assets/less/widgets/source-code.less',

                    //Extensions style
                    'assets/css/ep-cursor-effects.css'            : 'assets/less/extensions/cursor-effects.less',
                    'assets/css/ep-image-hover-effects.css'            : 'assets/less/extensions/image-hover-effects.less',
                    'assets/css/ep-tile-scroll.css'               : 'assets/less/extensions/tile-scroll.less',
                    'assets/css/ep-reveal-effects.css'            : 'assets/less/extensions/reveal-effects.less',
                    'assets/css/ep-ripple-click-effect.css'            : 'assets/less/extensions/ripple-click-effect.less',
                    'assets/css/ep-animated-gradient-background.css': 'assets/less/extensions/animated-gradient-background.less',
                    'assets/css/ep-context-menu.css'              : 'assets/less/extensions/context-menu.less',

                    'admin/assets/css/ep-product-feed.css'        : 'assets/less/product-feed.less',
                    'admin/assets/css/ep-admin.css'               : 'assets/less/admin.less',
                    'admin/assets/css/ep-notice.css'              : 'assets/less/notice.less',
                    'admin/assets/css/ep-megamenu-admin.css'      : 'assets/less/megamenu-admin.less',

                    // editor style
                    'includes/template-library/editor/assets/css/editor-template-library.css'   : 'includes/template-library/editor/assets/css/editor-template-library.less',

                    // Bundle style file
                    'assets/css/ep-styles.css': [
                        'assets/less/widgets/accordion.less',
                        'assets/less/widgets/comparison-list.less',
                        'assets/less/widgets/advanced-button.less',
                        'assets/less/widgets/advanced-counter.less',
                        'assets/less/widgets/advanced-divider.less',
                        'assets/less/widgets/advanced-heading.less',
                        'assets/less/widgets/advanced-icon-box.less',
                        'assets/less/widgets/advanced-image-gallery.less',
                        'assets/less/widgets/advanced-gmap.less',
                        'assets/less/widgets/advanced-progress-bar.less',
                        'assets/less/widgets/animated-heading.less',
                        'assets/less/widgets/audio-player.less',
                        'assets/less/widgets/booked-calendar.less',
                        'assets/less/widgets/business-hours.less',
                        'assets/less/widgets/call-out.less',
                        'assets/less/widgets/carousel.less',
                        'assets/less/widgets/changelog.less',
                        'assets/less/widgets/circle-menu.less',
                        'assets/less/widgets/contact-form.less',
                        'assets/less/widgets/cookie-consent.less',
                        'assets/less/widgets/countdown.less',
                        'assets/less/widgets/crypto-currency-card.less',
                        'assets/less/widgets/crypto-currency-table.less',
                        'assets/less/widgets/crypto-currency-carousel.less',
                        'assets/less/widgets/crypto-currency-chart.less',
                        'assets/less/widgets/crypto-currency-chart-carousel.less',
                        'assets/less/widgets/crypto-currency-grid.less',
                        'assets/less/widgets/crypto-currency-list.less',
                        'assets/less/widgets/crypto-currency-ticker.less',
                        'assets/less/widgets/icon-mobile-menu.less',
                        'assets/less/widgets/custom-carousel.less',
                        'assets/less/widgets/circle-info.less',
                        'assets/less/widgets/custom-gallery.less',
                        'assets/less/widgets/dark-mode.less',
                        'assets/less/widgets/device-slider.less',
                        'assets/less/widgets/dual-button.less',
                        'assets/less/widgets/dynamic-grid.less',
                        'assets/less/widgets/dynamic-carousel.less',
                        /**
                         * since v6.1.14
                         */
                        'assets/less/widgets/edd-category-grid.less',
                        'assets/less/widgets/edd-product.less',
                        'assets/less/widgets/edd-category-carousel.less',
                        'assets/less/widgets/edd-product-carousel.less',
                        'assets/less/widgets/edd-tabs.less',
                        'assets/less/widgets/edd-cart.less',
                        'assets/less/widgets/edd-checkout.less',

                        /**
                        * since v6.7.XX
                        */
                        'assets/less/widgets/edd-mini-cart.less',
                        'assets/less/widgets/edd-product-reviews.less',
                        'assets/less/widgets/edd-product-review-carousel.less',



                        'assets/less/widgets/fancy-list.less',
                        'assets/less/widgets/fancy-card.less',
                        'assets/less/widgets/fancy-icons.less',
                        'assets/less/widgets/fancy-slider.less',
                        'assets/less/widgets/fancy-tabs.less',
                        'assets/less/widgets/interactive-tabs.less',
                        'assets/less/widgets/faq.less',
                        'assets/less/widgets/flip-box.less',
                        'assets/less/widgets/helpdesk.less',
                        'assets/less/widgets/hover-box.less',
                        'assets/less/widgets/iconnav.less',
                        'assets/less/widgets/instagram.less',
                        'assets/less/widgets/image-parallax.less',
                        'assets/less/widgets/iframe.less',
                        'assets/less/widgets/lightbox.less',
                        'assets/less/widgets/lottie-icon-box.less',
                        'assets/less/widgets/logo-grid.less',
                        'assets/less/widgets/logo-carousel.less',
                        'assets/less/widgets/marker.less',
                        'assets/less/widgets/member.less',
                        'assets/less/widgets/navbar.less',
                        'assets/less/widgets/news-ticker.less',
                        'assets/less/widgets/offcanvas.less',
                        'assets/less/widgets/open-street-map.less',
                        'assets/less/widgets/panel-slider.less',
                        'assets/less/widgets/portfolio-gallery.less',
                        'assets/less/widgets/portfolio-list.less',
                        'assets/less/widgets/portfolio-carousel.less',
                        'assets/less/widgets/post-block-modern.less',
                        'assets/less/widgets/post-block.less',
                        'assets/less/widgets/post-card.less',
                        'assets/less/widgets/post-gallery.less',
                        'assets/less/widgets/post-grid-tab.less',
                        'assets/less/widgets/post-grid.less',
                        'assets/less/widgets/post-list.less',
                        'assets/less/widgets/post-slider.less',
                        'assets/less/widgets/price-list.less',
                        'assets/less/widgets/price-table.less',
                        'assets/less/widgets/profile-card.less',
                        'assets/less/widgets/progress-pie.less',
                        'assets/less/widgets/qrcode.less',
                        'assets/less/widgets/barcode.less',
                        'assets/less/widgets/svg-blob.less',
                        'assets/less/widgets/marquee.less',
                        'assets/less/widgets/mega-menu.less',
                        'assets/less/widgets/sub-menu.less',
                        'assets/less/widgets/scroll-button.less',
                        'assets/less/widgets/scroll-image.less',
                        'assets/less/widgets/scrollnav.less',
                        'assets/less/widgets/search.less',
                        'assets/less/widgets/single-post.less',
                        'assets/less/widgets/slider.less',
                        'assets/less/widgets/slideshow.less',
                        'assets/less/widgets/social-share.less',
                        'assets/less/widgets/social-proof.less',
                        'assets/less/widgets/switcher.less',
                        'assets/less/widgets/content-switcher.less',
                        'assets/less/widgets/table-of-content.less',
                        'assets/less/widgets/table.less',
                        'assets/less/widgets/tabs.less',
                        'assets/less/widgets/testimonial-carousel.less',
                        'assets/less/widgets/testimonial-grid.less',
                        'assets/less/widgets/testimonial-slider.less',
                        'assets/less/widgets/threesixty-product-viewer.less',
                        'assets/less/widgets/thumb-gallery.less',
                        'assets/less/widgets/timeline.less',
                        'assets/less/widgets/toggle.less',
                        'assets/less/widgets/trailer-box.less',
                        'assets/less/widgets/twitter-carousel.less',
                        'assets/less/widgets/twitter-grid.less',
                        'assets/less/widgets/twitter-slider.less',
                        'assets/less/widgets/tutor-lms.less',
                        'assets/less/widgets/learnpress-grid.less',
                        'assets/less/widgets/learnpress-carousel.less',
                        'assets/less/widgets/time-zone.less',
                        'assets/less/widgets/total-count.less',
                        'assets/less/widgets/user-login.less',
                        'assets/less/widgets/user-register.less',
                        'assets/less/widgets/vertical-menu.less',
                        'assets/less/widgets/slinky-vertical-menu.less',
                        'assets/less/widgets/video-gallery.less',
                        'assets/less/widgets/video-player.less',
                        'assets/less/widgets/weather.less',
                        'assets/less/widgets/webhook-form.less',
                        'assets/less/widgets/reading-progress.less',
                        'assets/less/widgets/google-reviews.less',
                        'assets/less/widgets/honeycombs.less',
                        'assets/less/widgets/step-flow.less',
                        'assets/less/widgets/featured-box.less',
                        'assets/less/widgets/image-compare.less',
                        'assets/less/widgets/interactive-card.less',
                        'assets/less/widgets/svg-maps.less',
                        'assets/less/widgets/image-accordion.less',
                        'assets/less/widgets/image-expand.less',
                        'assets/less/widgets/hover-video.less',
                        'assets/less/widgets/notification.less',
                        'assets/less/widgets/tags-cloud.less',
                        'assets/less/widgets/breadcrumbs.less',
                        'assets/less/widgets/coupon-code.less',
                        'assets/less/widgets/advanced-calculator.less',
                        'assets/less/widgets/animated-card.less',
                        'assets/less/widgets/animated-link.less',
                        'assets/less/widgets/review-card.less',
                        'assets/less/widgets/review-card-grid.less',
                        'assets/less/widgets/review-card-carousel.less',
                        'assets/less/widgets/static-carousel.less',
                        'assets/less/widgets/image-stack.less',
                        'assets/less/widgets/brand-grid.less',
                        'assets/less/widgets/brand-carousel.less',
                        'assets/less/widgets/creative-button.less',
                        'assets/less/widgets/static-grid-tab.less',
                        'assets/less/widgets/horizontal-scroller.less',
                        'assets/less/widgets/stacker.less',
                        'assets/less/widgets/events-calendar-grid.less',
                        'assets/less/widgets/events-calendar-carousel.less',
                        'assets/less/widgets/events-calendar-list.less',
                        'assets/less/widgets/wc-add-to-cart.less',
                        'assets/less/widgets/wc-carousel.less',
                        'assets/less/widgets/wc-categories.less',
                        'assets/less/widgets/wc-elements.less',
                        'assets/less/widgets/wc-mini-cart.less',
                        'assets/less/widgets/wc-products.less',
                        'assets/less/widgets/wc-slider.less',
                        'assets/less/widgets/charitable-campaigns.less',
                        'assets/less/widgets/charitable-donation-form.less',
                        'assets/less/widgets/charitable-donations.less',
                        'assets/less/widgets/charitable-donors.less',
                        'assets/less/widgets/charitable-login.less',
                        'assets/less/widgets/charitable-profile.less',
                        'assets/less/widgets/charitable-registration.less',
                        'assets/less/widgets/charitable-stat.less',
                        'assets/less/widgets/give-donation-history.less',
                        'assets/less/widgets/give-donor-wall.less',
                        'assets/less/widgets/give-form.less',
                        'assets/less/widgets/give-form-grid.less',
                        'assets/less/widgets/give-goal.less',
                        'assets/less/widgets/give-login.less',
                        'assets/less/widgets/give-profile-editor.less',
                        'assets/less/widgets/give-receipt.less',
                        'assets/less/widgets/give-register.less',
                        'assets/less/widgets/remote-arrows.less',
                        'assets/less/widgets/remote-thumbs.less',
                        'assets/less/widgets/remote-pagination.less',
                        'assets/less/widgets/remote-fraction.less',
                        'assets/less/widgets/product-grid.less',
                        'assets/less/widgets/product-carousel.less',
                        'assets/less/widgets/facebook-feed.less',
                        'assets/less/widgets/facebook-feed-carousel.less',
                        'assets/less/widgets/floating-knowledgebase.less',

                        // Extensions styles
                        'assets/less/extensions/cursor-effects.less',
                        'assets/less/extensions/image-hover-effects.less',
                        'assets/less/extensions/tippy.less',
                        'assets/less/extensions/tile-scroll.less',
                        'assets/less/extensions/reveal-effects.less',
                        'assets/less/extensions/ripple-click-effect.less',
                        'assets/less/extensions/animated-gradient-background.less',
                        'assets/less/extensions/context-menu.less',

                        'assets/less/third-party-widgets/jquery-mThumbnailScroller.less',
                        'assets/less/third-party-widgets/download-monitor.less',
                        'assets/less/third-party-widgets/fluent-forms.less',
                        'assets/less/third-party-widgets/everest-forms.less',
                        'assets/less/third-party-widgets/formidable-forms.less',
                        'assets/less/third-party-widgets/forminator-forms.less',
                        'assets/less/third-party-widgets/gravity-forms.less',
                        'assets/less/third-party-widgets/give.less',
                        'assets/less/third-party-widgets/mailchimp.less',
                        'assets/less/third-party-widgets/twentytwenty.less',
                        'assets/less/third-party-widgets/the-newsletter.less',
                        'assets/less/third-party-widgets/datatables.less',
                        'assets/less/third-party-widgets/datatables.uikit.less',
                        'assets/less/third-party-widgets/imagezoom.less',
                        'assets/less/font.less',
                        'assets/less/third-party-widgets/woocommerce.less',
                    ]
                }
            }
        },

        rtlcss: {
            siteRTL: {
                // task options
                options: {
                    // rtlcss options
                    opts: {
                        clean: true
                    },
                    // rtlcss plugins
                    plugins: [],
                    // save unmodified files
                    saveUnmodified: true
                },
                expand: true,
                cwd: 'assets/css/',
                dest: 'assets/css/',
                src: ['**/*.css', '!**/*.rtl.css'],
                ext: '.rtl.css'
            },
            adminRTL: {
                // task options
                options: {
                    // rtlcss options
                    opts: {
                        clean: true
                    },
                    // rtlcss plugins
                    plugins: [],
                    // save unmodified files
                    saveUnmodified: true
                },
                expand: true,
                cwd: 'admin/assets/css/',
                dest: 'admin/assets/css/',
                src: ['**/*.css', '!**/*.rtl.css'],
                ext: '.rtl.css'
            }
        },

        concat: {
          js: {
              src: [
                    'assets/js/common/helper.js',
                    'assets/js/modules/ep-accordion.js',
                    'assets/js/modules/ep-advanced-calculator.js',
                    'assets/js/modules/ep-advanced-counter.js',
                    'assets/js/modules/ep-advanced-divider.js',
                    'assets/js/modules/ep-advanced-gmap.js',
                    'assets/js/modules/ep-advanced-heading.js',
                    'assets/js/modules/ep-advanced-icon-box.js',
                    'assets/js/modules/ep-advanced-image-gallery.js',
                    'assets/js/modules/ep-advanced-progress-bar.js',
                    'assets/js/modules/ep-age-gate.js',
                    'assets/js/modules/ep-animated-gradient-background.js',
                    'assets/js/modules/ep-animated-heading.js',
                    'assets/js/modules/ep-audio-player.js',
                    'assets/js/modules/ep-background-overlay.js',
                    'assets/js/modules/ep-background-parallax.js',
                    'assets/js/modules/ep-barcode.js',
                    'assets/js/modules/ep-svg-blob.js',
                    'assets/js/modules/ep-marquee.js',
                    'assets/js/modules/ep-post-grid.js',
                    'assets/js/modules/ep-mega-menu.js',
                    'assets/js/modules/ep-brand-carousel.js',
                    'assets/js/modules/ep-business-hours.js',
                    'assets/js/modules/ep-carousel.js',
                    'assets/js/modules/ep-chart.js',
                    'assets/js/modules/ep-circle-info.js',
                    'assets/js/modules/ep-circle-menu.js',
                    'assets/js/modules/ep-comment.js',
                    'assets/js/modules/ep-confetti-effects.js',
                    'assets/js/modules/ep-ripple-click-effect.js',
                    'assets/js/modules/ep-contact-form.js',
                    'assets/js/modules/ep-cookie-consent.js',
                    'assets/js/modules/ep-countdown.js',
                    'assets/js/modules/ep-coupon-code.js',
                    'assets/js/modules/ep-cursor-effects.js',
                    'assets/js/modules/ep-custom-carousel.js',
                    'assets/js/modules/ep-custom-gallery.js',
                    'assets/js/modules/ep-dark-mode.js',
                    'assets/js/modules/ep-dynamic-carousel.js',
                    'assets/js/modules/ep-background-expand.js',
                    'assets/js/modules/ep-webhook-form.js',

                    /**
                     * since v6.1.14
                     */
                    'assets/js/modules/ep-edd-product-review-carousel.js',
                    'assets/js/modules/ep-edd-category-carousel.js',
                    'assets/js/modules/ep-edd-product-carousel.js',
                    'assets/js/modules/ep-edd-tabs.js',

                    'assets/js/modules/ep-events-calendar-carousel.js',
                    'assets/js/modules/ep-fancy-slider.js',
                    'assets/js/modules/ep-fancy-tabs.js',
                    'assets/js/modules/ep-faq.js',
                    'assets/js/modules/ep-flip-box.js',
                    'assets/js/modules/ep-floating-effects.js',
                    'assets/js/modules/ep-helpdesk.js',
                    'assets/js/modules/ep-honeycombs.js',
                    'assets/js/modules/ep-horizontal-scroller.js',
                    'assets/js/modules/ep-stacker.js',
                    'assets/js/modules/ep-hover-box.js',
                    'assets/js/modules/ep-hover-video.js',
                    'assets/js/modules/ep-iconnav.js',
                    'assets/js/modules/ep-iframe.js',
                    'assets/js/modules/ep-image-accordion.js',
                    'assets/js/modules/ep-image-compare.js',
                    'assets/js/modules/ep-image-expand.js',
                    'assets/js/modules/ep-image-magnifier.js',
                    'assets/js/modules/ep-image-parallax.js',
                    'assets/js/modules/ep-image-stack.js',
                    'assets/js/modules/ep-instagram.js',
                    'assets/js/modules/ep-interactive-card.js',
                    'assets/js/modules/ep-svg-maps.js',
                    'assets/js/modules/ep-interactive-tabs.js',
                    'assets/js/modules/ep-logo-carousel.js',
                    'assets/js/modules/ep-logo-grid.js',
                    'assets/js/modules/ep-lottie-icon-box.js',
                    'assets/js/modules/ep-lottie-image.js',
                    'assets/js/modules/ep-mailchimp.js',
                    'assets/js/modules/ep-marker.js',
                    'assets/js/modules/ep-modal.js',
                    'assets/js/modules/ep-news-ticker.js',
                    'assets/js/modules/ep-notation.js',
                    'assets/js/modules/ep-notification.js',
                    'assets/js/modules/ep-offcanvas.js',
                    'assets/js/modules/ep-open-street-map.js',
                    'assets/js/modules/ep-panel-slider.js',
                    'assets/js/modules/ep-parallax-effects.js',
                    'assets/js/modules/ep-particles.js',
                    'assets/js/modules/ep-portfolio-carousel.js',
                    'assets/js/modules/ep-portfolio-gallery.js',
                    'assets/js/modules/ep-post-gallery.js',
                    'assets/js/modules/ep-post-grid-tab.js',
                    'assets/js/modules/ep-price-table.js',
                    'assets/js/modules/ep-progress-pie.js',
                    'assets/js/modules/ep-qrcode.js',
                    'assets/js/modules/ep-reading-progress.js',
                    'assets/js/modules/ep-reading-timer.js',
                    'assets/js/modules/ep-reveal-effects.js',
                    'assets/js/modules/ep-review-card-carousel.js',
                    'assets/js/modules/ep-scroll-button.js',
                    'assets/js/modules/ep-scrollnav.js',
                    'assets/js/modules/ep-search.js',
                    'assets/js/modules/ep-section-sticky.js',
                    'assets/js/modules/ep-slider.js',
                    'assets/js/modules/ep-slideshow.js',
                    'assets/js/modules/ep-slinky-vertical-menu.js',
                    'assets/js/modules/ep-sound-effects.js',
                    'assets/js/modules/ep-source-code.js',
                    'assets/js/modules/ep-product-carousel.js',
                    'assets/js/modules/ep-static-carousel.js',
                    'assets/js/modules/ep-static-grid-tab.js',
                    'assets/js/modules/ep-step-flow.js',
                    'assets/js/modules/ep-switcher.js',
                    'assets/js/modules/ep-content-switcher.js',
                    'assets/js/modules/ep-svg-image.js',
                    'assets/js/modules/ep-text-read-more.js',
                    'assets/js/modules/ep-table-of-content.js',
                    'assets/js/modules/ep-table.js',
                    'assets/js/modules/ep-tabs.js',
                    'assets/js/modules/ep-tags-cloud.js',
                    'assets/js/modules/ep-testimonial-carousel.js',
                    'assets/js/modules/ep-testimonial-slider.js',
                    'assets/js/modules/ep-threed-text.js',
                    'assets/js/modules/ep-threesixty-product-viewer.js',
                    'assets/js/modules/ep-tile-scroll.js',
                    'assets/js/modules/ep-time-zone.js',
                    'assets/js/modules/ep-timeline.js',
                    'assets/js/modules/ep-toggle.js',
                    'assets/js/modules/ep-tooltip.js',
                    'assets/js/modules/ep-total-count.js',
                    'assets/js/modules/ep-tutor-lms-course-grid.js',
                    'assets/js/modules/ep-tutor-lms-course-carousel.js',
                    'assets/js/modules/ep-learnpress-carousel.js',
                    'assets/js/modules/ep-twitter-carousel.js',
                    'assets/js/modules/ep-twitter-slider.js',
                    'assets/js/modules/ep-user-login.js',
                    'assets/js/modules/ep-user-register.js',
                    'assets/js/modules/ep-vertical-menu.js',
                    'assets/js/modules/ep-video-gallery.js',
                    'assets/js/modules/ep-wc-products.js',
                    'assets/js/modules/ep-weather.js',
                    'assets/js/modules/ep-wrapper-link.js',
                    'assets/js/modules/ep-remote-arrows.js',
                    'assets/js/modules/ep-remote-thumbs.js',
                    'assets/js/modules/ep-remote-pagination.js',
                    'assets/js/modules/ep-remote-fraction.js',
                    'assets/js/modules/ep-hash-link.js',
                    'assets/js/modules/ep-facebook-feed-carousel.js',
                    'assets/js/modules/ep-crypto-currency-card.js',
                    'assets/js/modules/ep-crypto-currency-table.js',
                    'assets/js/modules/ep-crypto-currency-grid.js',
                    'assets/js/modules/ep-crypto-currency-list.js',
                    'assets/js/modules/ep-crypto-currency-carousel.js',
                    'assets/js/modules/ep-crypto-currency-chart.js',
                    'assets/js/modules/ep-crypto-currency-chart-carousel.js',
                    'assets/js/modules/ep-crypto-currency-ticker.js',
                    'assets/js/modules/ep-realistic-image-shadow.js',
                    'assets/js/modules/ep-floating-knowledgebase.js',
              ],
              dest: 'assets/js/ep-scripts.js',
              // options: {
              //     banner: ';(function($, elementor){\n\'use strict\';\n',
              //     footer: '\n})(jQuery, window.elementorFrontend);'
              // },
          }
        },

        terser: {
            options: {
                mangle: true
            },
            my_target: {
                files: {
                    'assets/js/common/helper.min.js'                           : [ 'assets/js/common/helper.js' ],
                    'assets/js/modules/ep-accordion.min.js'                    : [ 'assets/js/modules/ep-accordion.js' ],
                    'assets/js/modules/ep-advanced-calculator.min.js'          : [ 'assets/js/modules/ep-advanced-calculator.js' ],
                    'assets/js/modules/ep-advanced-counter.min.js'             : [ 'assets/js/modules/ep-advanced-counter.js' ],
                    'assets/js/modules/ep-advanced-divider.min.js'             : [ 'assets/js/modules/ep-advanced-divider.js' ],
                    'assets/js/modules/ep-advanced-gmap.min.js'                : [ 'assets/js/modules/ep-advanced-gmap.js' ],
                    'assets/js/modules/ep-advanced-heading.min.js'             : [ 'assets/js/modules/ep-advanced-heading.js' ],
                    'assets/js/modules/ep-advanced-icon-box.min.js'            : [ 'assets/js/modules/ep-advanced-icon-box.js' ],
                    'assets/js/modules/ep-advanced-image-gallery.min.js'       : [ 'assets/js/modules/ep-advanced-image-gallery.js' ],
                    'assets/js/modules/ep-advanced-progress-bar.min.js'        : [ 'assets/js/modules/ep-advanced-progress-bar.js' ],
                    'assets/js/modules/ep-age-gate.min.js'                     : [ 'assets/js/modules/ep-age-gate.js' ],
                    'assets/js/modules/ep-animated-gradient-background.min.js' : [ 'assets/js/modules/ep-animated-gradient-background.js' ],
                    'assets/js/modules/ep-animated-heading.min.js'             : [ 'assets/js/modules/ep-animated-heading.js' ],
                    'assets/js/modules/ep-audio-player.min.js'                 : [ 'assets/js/modules/ep-audio-player.js' ],
                    'assets/js/modules/ep-background-overlay.min.js'           : [ 'assets/js/modules/ep-background-overlay.js' ],
                    'assets/js/modules/ep-background-parallax.min.js'          : [ 'assets/js/modules/ep-background-parallax.js' ],
                    'assets/js/modules/ep-barcode.min.js'                      : [ 'assets/js/modules/ep-barcode.js' ],
                    'assets/js/modules/ep-svg-blob.min.js'                     : [ 'assets/js/modules/ep-svg-blob.js' ],
                    'assets/js/modules/ep-marquee.min.js'                      : [ 'assets/js/modules/ep-marquee.js' ],
                    'assets/js/modules/ep-post-grid.min.js'                    : [ 'assets/js/modules/ep-post-grid.js' ],
                    'assets/js/modules/ep-mega-menu.min.js'                    : [ 'assets/js/modules/ep-mega-menu.js' ],
                    'assets/js/modules/ep-brand-carousel.min.js'               : [ 'assets/js/modules/ep-brand-carousel.js' ],
                    'assets/js/modules/ep-business-hours.min.js'               : [ 'assets/js/modules/ep-business-hours.js' ],
                    'assets/js/modules/ep-carousel.min.js'                     : [ 'assets/js/modules/ep-carousel.js' ],
                    'assets/js/modules/ep-chart.min.js'                        : [ 'assets/js/modules/ep-chart.js' ],
                    'assets/js/modules/ep-circle-info.min.js'                  : [ 'assets/js/modules/ep-circle-info.js' ],
                    'assets/js/modules/ep-circle-menu.min.js'                  : [ 'assets/js/modules/ep-circle-menu.js' ],
                    'assets/js/modules/ep-comment.min.js'                      : [ 'assets/js/modules/ep-comment.js' ],
                    'assets/js/modules/ep-confetti-effects.min.js'             : [ 'assets/js/modules/ep-confetti-effects.js' ],
                    'assets/js/modules/ep-ripple-click-effect.min.js'             : [ 'assets/js/modules/ep-ripple-click-effect.js' ],
                    'assets/js/modules/ep-contact-form.min.js'                 : [ 'assets/js/modules/ep-contact-form.js' ],
                    'assets/js/modules/ep-cookie-consent.min.js'               : [ 'assets/js/modules/ep-cookie-consent.js' ],
                    'assets/js/modules/ep-countdown.min.js'                    : [ 'assets/js/modules/ep-countdown.js' ],
                    'assets/js/modules/ep-coupon-code.min.js'                  : [ 'assets/js/modules/ep-coupon-code.js' ],
                    'assets/js/modules/ep-cursor-effects.min.js'               : [ 'assets/js/modules/ep-cursor-effects.js' ],
                    'assets/js/modules/ep-custom-carousel.min.js'              : [ 'assets/js/modules/ep-custom-carousel.js' ],
                    'assets/js/modules/ep-custom-gallery.min.js'               : [ 'assets/js/modules/ep-custom-gallery.js' ],
                    'assets/js/modules/ep-dark-mode.min.js'                    : [ 'assets/js/modules/ep-dark-mode.js' ],
                    'assets/js/modules/ep-dynamic-carousel.min.js'             : [ 'assets/js/modules/ep-dynamic-carousel.js' ],
                    'assets/js/modules/ep-background-expand.min.js'            : [ 'assets/js/modules/ep-background-expand.js' ],
                    'assets/js/modules/ep-webhook-form.min.js'                 : [ 'assets/js/modules/ep-webhook-form.js' ],

                    /**
                     * since v6.1.14
                     */
                    'assets/js/modules/ep-edd-product-review-carousel.min.js'  : ['assets/js/modules/ep-edd-product-review-carousel.js',],
                    'assets/js/modules/ep-edd-category-carousel.min.js'        : [ 'assets/js/modules/ep-edd-category-carousel.js' ],
                    'assets/js/modules/ep-edd-product-carousel.min.js'         : [ 'assets/js/modules/ep-edd-product-carousel.js' ],
                    'assets/js/modules/ep-edd-tabs.min.js'                     : [ 'assets/js/modules/ep-edd-tabs.js' ],

                    'assets/js/modules/ep-events-calendar-carousel.min.js'     : [ 'assets/js/modules/ep-events-calendar-carousel.js' ],
                    'assets/js/modules/ep-fancy-slider.min.js'                 : [ 'assets/js/modules/ep-fancy-slider.js' ],
                    'assets/js/modules/ep-fancy-tabs.min.js'                   : [ 'assets/js/modules/ep-fancy-tabs.js' ],
                    'assets/js/modules/ep-faq.min.js'                          : [ 'assets/js/modules/ep-faq.js' ],
                    'assets/js/modules/ep-flip-box.min.js'                      : [ 'assets/js/modules/ep-flip-box.js' ],
                    'assets/js/modules/ep-floating-effects.min.js'             : [ 'assets/js/modules/ep-floating-effects.js' ],
                    'assets/js/modules/ep-helpdesk.min.js'                     : [ 'assets/js/modules/ep-helpdesk.js' ],
                    'assets/js/modules/ep-honeycombs.min.js'                   : [ 'assets/js/modules/ep-honeycombs.js' ],
                    'assets/js/modules/ep-horizontal-scroller.min.js'          : [ 'assets/js/modules/ep-horizontal-scroller.js' ],
                    'assets/js/modules/ep-stacker.min.js'                      : [ 'assets/js/modules/ep-stacker.js' ],
                    'assets/js/modules/ep-hover-box.min.js'                    : [ 'assets/js/modules/ep-hover-box.js' ],
                    'assets/js/modules/ep-hover-video.min.js'                  : [ 'assets/js/modules/ep-hover-video.js' ],
                    'assets/js/modules/ep-iconnav.min.js'                      : [ 'assets/js/modules/ep-iconnav.js' ],
                    'assets/js/modules/ep-iframe.min.js'                       : [ 'assets/js/modules/ep-iframe.js' ],
                    'assets/js/modules/ep-image-accordion.min.js'              : [ 'assets/js/modules/ep-image-accordion.js' ],
                    'assets/js/modules/ep-image-compare.min.js'                : [ 'assets/js/modules/ep-image-compare.js' ],
                    'assets/js/modules/ep-image-expand.min.js'                 : [ 'assets/js/modules/ep-image-expand.js' ],
                    'assets/js/modules/ep-image-magnifier.min.js'              : [ 'assets/js/modules/ep-image-magnifier.js' ],
                    'assets/js/modules/ep-image-parallax.min.js'               : [ 'assets/js/modules/ep-image-parallax.js' ],
                    'assets/js/modules/ep-image-stack.min.js'                  : [ 'assets/js/modules/ep-image-stack.js' ],
                    'assets/js/modules/ep-instagram.min.js'                    : [ 'assets/js/modules/ep-instagram.js' ],
                    'assets/js/modules/ep-interactive-card.min.js'             : [ 'assets/js/modules/ep-interactive-card.js' ],
                    'assets/js/modules/ep-svg-maps.min.js'                     : [ 'assets/js/modules/ep-svg-maps.js' ],
                    'assets/js/modules/ep-interactive-tabs.min.js'             : [ 'assets/js/modules/ep-interactive-tabs.js' ],
                    'assets/js/modules/ep-logo-carousel.min.js'                : [ 'assets/js/modules/ep-logo-carousel.js' ],
                    'assets/js/modules/ep-logo-grid.min.js'                    : [ 'assets/js/modules/ep-logo-grid.js' ],
                    'assets/js/modules/ep-lottie-icon-box.min.js'              : [ 'assets/js/modules/ep-lottie-icon-box.js' ],
                    'assets/js/modules/ep-lottie-image.min.js'                 : [ 'assets/js/modules/ep-lottie-image.js' ],
                    'assets/js/modules/ep-mailchimp.min.js'                    : [ 'assets/js/modules/ep-mailchimp.js' ],
                    'assets/js/modules/ep-marker.min.js'                       : [ 'assets/js/modules/ep-marker.js' ],
                    'assets/js/modules/ep-modal.min.js'                        : [ 'assets/js/modules/ep-modal.js' ],
                    'assets/js/modules/ep-news-ticker.min.js'                  : [ 'assets/js/modules/ep-news-ticker.js' ],
                    'assets/js/modules/ep-notation.min.js'                     : [ 'assets/js/modules/ep-notation.js' ],
                    'assets/js/modules/ep-notification.min.js'                 : [ 'assets/js/modules/ep-notification.js' ],
                    'assets/js/modules/ep-offcanvas.min.js'                    : [ 'assets/js/modules/ep-offcanvas.js' ],
                    'assets/js/modules/ep-open-street-map.min.js'              : [ 'assets/js/modules/ep-open-street-map.js' ],
                    'assets/js/modules/ep-panel-slider.min.js'                 : [ 'assets/js/modules/ep-panel-slider.js' ],
                    'assets/js/modules/ep-parallax-effects.min.js'             : [ 'assets/js/modules/ep-parallax-effects.js' ],
                    'assets/js/modules/ep-particles.min.js'                    : [ 'assets/js/modules/ep-particles.js' ],
                    'assets/js/modules/ep-portfolio-carousel.min.js'           : [ 'assets/js/modules/ep-portfolio-carousel.js' ],
                    'assets/js/modules/ep-portfolio-gallery.min.js'            : [ 'assets/js/modules/ep-portfolio-gallery.js' ],
                    'assets/js/modules/ep-post-gallery.min.js'                 : [ 'assets/js/modules/ep-post-gallery.js' ],
                    'assets/js/modules/ep-post-grid-tab.min.js'                : [ 'assets/js/modules/ep-post-grid-tab.js' ],
                    'assets/js/modules/ep-price-table.min.js'                  : [ 'assets/js/modules/ep-price-table.js' ],
                    'assets/js/modules/ep-progress-pie.min.js'                 : [ 'assets/js/modules/ep-progress-pie.js' ],
                    'assets/js/modules/ep-qrcode.min.js'                       : [ 'assets/js/modules/ep-qrcode.js' ],
                    'assets/js/modules/ep-reading-progress.min.js'             : [ 'assets/js/modules/ep-reading-progress.js' ],
                    'assets/js/modules/ep-reading-timer.min.js'                : [ 'assets/js/modules/ep-reading-timer.js' ],
                    'assets/js/modules/ep-reveal-effects.min.js'               : [ 'assets/js/modules/ep-reveal-effects.js' ],
                    'assets/js/modules/ep-review-card-carousel.min.js'         : [ 'assets/js/modules/ep-review-card-carousel.js' ],
                    'assets/js/modules/ep-scroll-button.min.js'                : [ 'assets/js/modules/ep-scroll-button.js' ],
                    'assets/js/modules/ep-scrollnav.min.js'                    : [ 'assets/js/modules/ep-scrollnav.js' ],
                    'assets/js/modules/ep-search.min.js'                       : [ 'assets/js/modules/ep-search.js' ],
                    'assets/js/modules/ep-section-sticky.min.js'               : [ 'assets/js/modules/ep-section-sticky.js' ],
                    'assets/js/modules/ep-slider.min.js'                       : [ 'assets/js/modules/ep-slider.js' ],
                    'assets/js/modules/ep-slideshow.min.js'                    : [ 'assets/js/modules/ep-slideshow.js' ],
                    'assets/js/modules/ep-slinky-vertical-menu.min.js'         : [ 'assets/js/modules/ep-slinky-vertical-menu.js' ],
                    'assets/js/modules/ep-sound-effects.min.js'                : [ 'assets/js/modules/ep-sound-effects.js' ],
                    'assets/js/modules/ep-source-code.min.js'                  : [ 'assets/js/modules/ep-source-code.js' ],
                    'assets/js/modules/ep-product-carousel.min.js'             : [ 'assets/js/modules/ep-product-carousel.js' ],
                    'assets/js/modules/ep-static-carousel.min.js'              : [ 'assets/js/modules/ep-static-carousel.js' ],
                    'assets/js/modules/ep-static-grid-tab.min.js'              : [ 'assets/js/modules/ep-static-grid-tab.js' ],
                    'assets/js/modules/ep-step-flow.min.js'                    : [ 'assets/js/modules/ep-step-flow.js' ],
                    'assets/js/modules/ep-switcher.min.js'                     : [ 'assets/js/modules/ep-switcher.js' ],
                    'assets/js/modules/ep-content-switcher.min.js'             : [ 'assets/js/modules/ep-content-switcher.js' ],
                    'assets/js/modules/ep-svg-image.min.js'                    : [ 'assets/js/modules/ep-svg-image.js' ],
                    'assets/js/modules/ep-text-read-more.min.js'               : [ 'assets/js/modules/ep-text-read-more.js' ],
                    'assets/js/modules/ep-table-of-content.min.js'             : [ 'assets/js/modules/ep-table-of-content.js' ],
                    'assets/js/modules/ep-table.min.js'                        : [ 'assets/js/modules/ep-table.js' ],
                    'assets/js/modules/ep-tabs.min.js'                         : [ 'assets/js/modules/ep-tabs.js' ],
                    'assets/js/modules/ep-tags-cloud.min.js'                   : [ 'assets/js/modules/ep-tags-cloud.js' ],
                    'assets/js/modules/ep-testimonial-carousel.min.js'         : [ 'assets/js/modules/ep-testimonial-carousel.js' ],
                    'assets/js/modules/ep-testimonial-slider.min.js'           : [ 'assets/js/modules/ep-testimonial-slider.js' ],
                    'assets/js/modules/ep-threed-text.min.js'                  : [ 'assets/js/modules/ep-threed-text.js' ],
                    'assets/js/modules/ep-threesixty-product-viewer.min.js'    : [ 'assets/js/modules/ep-threesixty-product-viewer.js' ],
                    'assets/js/modules/ep-tile-scroll.min.js'                  : [ 'assets/js/modules/ep-tile-scroll.js' ],
                    'assets/js/modules/ep-time-zone.min.js'                    : [ 'assets/js/modules/ep-time-zone.js' ],
                    'assets/js/modules/ep-timeline.min.js'                     : [ 'assets/js/modules/ep-timeline.js' ],
                    'assets/js/modules/ep-toggle.min.js'                       : [ 'assets/js/modules/ep-toggle.js' ],
                    'assets/js/modules/ep-tooltip.min.js'                      : [ 'assets/js/modules/ep-tooltip.js' ],
                    'assets/js/modules/ep-total-count.min.js'                  : [ 'assets/js/modules/ep-total-count.js' ],
                    'assets/js/modules/ep-tutor-lms-course-grid.min.js'        : [ 'assets/js/modules/ep-tutor-lms-course-grid.js' ],
                    'assets/js/modules/ep-tutor-lms-course-carousel.min.js'    : [ 'assets/js/modules/ep-tutor-lms-course-carousel.js' ],
                    'assets/js/modules/ep-learnpress-carousel.min.js'          : [ 'assets/js/modules/ep-learnpress-carousel.js' ],
                    'assets/js/modules/ep-twitter-carousel.min.js'             : [ 'assets/js/modules/ep-twitter-carousel.js' ],
                    'assets/js/modules/ep-twitter-slider.min.js'               : [ 'assets/js/modules/ep-twitter-slider.js' ],
                    'assets/js/modules/ep-user-login.min.js'                   : [ 'assets/js/modules/ep-user-login.js' ],
                    'assets/js/modules/ep-user-register.min.js'                : [ 'assets/js/modules/ep-user-register.js' ],
                    'assets/js/modules/ep-vertical-menu.min.js'                : [ 'assets/js/modules/ep-vertical-menu.js' ],
                    'assets/js/modules/ep-video-gallery.min.js'                : [ 'assets/js/modules/ep-video-gallery.js' ],
                    'assets/js/modules/ep-weather.min.js'                      : [ 'assets/js/modules/ep-weather.js' ],
                    'assets/js/modules/ep-wrapper-link.min.js'                 : [ 'assets/js/modules/ep-wrapper-link.js' ],
                    'assets/js/modules/ep-remote-arrows.min.js'                : [ 'assets/js/modules/ep-remote-arrows.js' ],
                    'assets/js/modules/ep-remote-thumbs.min.js'                : [ 'assets/js/modules/ep-remote-thumbs.js' ],
                    'assets/js/modules/ep-remote-pagination.min.js'            : [ 'assets/js/modules/ep-remote-pagination.js' ],
                    'assets/js/modules/ep-remote-fraction.min.js'              : [ 'assets/js/modules/ep-remote-fraction.js' ],
                    'assets/js/modules/ep-hash-link.min.js'                    : [ 'assets/js/modules/ep-hash-link.js' ],
                    'assets/js/modules/ep-facebook-feed-carousel.min.js'       : [ 'assets/js/modules/ep-facebook-feed-carousel.js' ],
                    'assets/js/modules/ep-crypto-currency-card.min.js'         : [ 'assets/js/modules/ep-crypto-currency-card.js' ],
                    'assets/js/modules/ep-crypto-currency-table.min.js'        : [ 'assets/js/modules/ep-crypto-currency-table.js' ],
                    'assets/js/modules/ep-crypto-currency-grid.min.js'         : [ 'assets/js/modules/ep-crypto-currency-grid.js' ],
                    'assets/js/modules/ep-crypto-currency-list.min.js'         : [ 'assets/js/modules/ep-crypto-currency-list.js' ],
                    'assets/js/modules/ep-crypto-currency-carousel.min.js'     : [ 'assets/js/modules/ep-crypto-currency-carousel.js' ],
                    'assets/js/modules/ep-crypto-currency-chart.min.js'        : [ 'assets/js/modules/ep-crypto-currency-chart.js' ],
                    'assets/js/modules/ep-crypto-currency-chart-carousel.min.js' : [ 'assets/js/modules/ep-crypto-currency-chart-carousel.js' ],
                    'assets/js/modules/ep-crypto-currency-ticker.min.js'       : [ 'assets/js/modules/ep-crypto-currency-ticker.js' ],
                    'assets/js/modules/ep-realistic-image-shadow.min.js'       : [ 'assets/js/modules/ep-realistic-image-shadow.js' ],
                    'assets/js/modules/ep-floating-knowledgebase.min.js'       : [ 'assets/js/modules/ep-floating-knowledgebase.js' ],

                    'assets/js/ep-scripts.min.js'                               : ['assets/js/ep-scripts.js'],
                    'assets/js/ep-editor.min.js'                                : ['assets/js/ep-editor.js'],
                    'admin/assets/js/ep-admin.min.js'                           : ['admin/assets/js/ep-admin.js'],
                    'admin/assets/js/ep-megamenu-admin.min.js'                  : ['admin/assets/js/ep-megamenu-admin.js'],

                    //admin js
                    'includes/template-library/editor/assets/js/editor-template-library.min.js' : ['includes/template-library/editor/assets/js/editor-template-library.js'],
                    'includes/live-copy/assets/xdLocalStorage.min.js'                           : ['includes/live-copy/assets/xdLocalStorage.js'],
                    'includes/live-copy/assets/ep-live-copy.min.js'                             : ['includes/live-copy/assets/ep-live-copy.js'],
                    'includes/controls/assets/js/ep-dynamic-select.min.js'                      : ['includes/controls/assets/js/ep-dynamic-select.js'],
                }
            }
        },

        watch: {
            styles: {
                files: ['assets/less/**/*.less'], // which files to watch
                tasks: ['less', 'rtlcss'],
                options: {
                    nospawn: true
                }
            },
            scripts: {
                files: ['assets/js/**/*.js', 'admin/assets/js/**/*.js'],
                tasks: ['concat', 'terser'],
                options: {
                  spawn: false,
                },
            }
        },



        // Element Pack Lite Version File manage //
        // Element Pack Lite Version File manage //

        copy: {
          main: {
            files: [
              // includes files within path
              {expand: true, src: [

                //Others Files
                'admin/assets/**',
                'admin/optimizer/**',
                'admin/admin-feeds.php',
                'admin/admin-notice.php',
                'assets/others/**',
                'assets/sounds/**',
                'assets/images/**',
                'assets/fonts/**',
                'base/**',
                'traits/*',
                'includes/compatiblity/**',
                'includes/controls/**',
                'includes/live-copy/**',
                'includes/template-library/**',
                'includes/twitteroauth/**',
                'includes/widgets/**',
                'includes/class-elements-wpml-compatibility.php',
                'includes/class-fb-access-token-generator-control.php',
                'includes/class-google-recaptcha.php',
                'includes/class-json-file-upload-control.php',
                'includes/class-parsedown.php',
                'includes/class-rooten-theme-compatibility.php',
                'includes/class-svg-support.php',
                'includes/class-duplicator.php',
                'includes/controls.php',
                'includes/element-pack-filters.php',
                'includes/helper.php',
                'includes/modules-manager.php',
                'includes/utils.php',

                // Common CSS
                'assets/css/bdt-uikit.css',
                'assets/css/bdt-uikit.rtl.css',
                'assets/css/ep-styles.css',
                'assets/css/ep-styles.rtl.css',
                'assets/css/ep-font.css',
                'assets/css/ep-font.rtl.css',
                'assets/css/ep-helper.css',
                'assets/css/ep-helper.rtl.css',
                'assets/css/ep-editor.css',
                'assets/css/ep-editor.rtl.css',
                'assets/css/ep-preview.css',
                'assets/css/ep-preview.rtl.css',

                // Widget CSS
                'assets/css/ep-accordion.css',
                'assets/css/ep-accordion.rtl.css',
                'assets/css/ep-animated-link.css',
                'assets/css/ep-animated-link.rtl.css',
                'assets/css/ep-business-hours.css',
                'assets/css/ep-business-hours.rtl.css',
                'assets/css/ep-brand-grid.css',
                'assets/css/ep-brand-grid.rtl.css',
                'assets/css/ep-call-out.css',
                'assets/css/ep-call-out.rtl.css',
                'assets/css/ep-creative-button.css',
                'assets/css/ep-creative-button.rtl.css',
                'assets/css/ep-contact-form.css',
                'assets/css/ep-contact-form.rtl.css',
                'assets/css/ep-cookie-consent.css',
                'assets/css/ep-cookie-consent.rtl.css',
                'assets/css/ep-countdown.css',
                'assets/css/ep-countdown.rtl.css',
                'assets/css/ep-custom-gallery.css',
                'assets/css/ep-custom-gallery.rtl.css',
                'assets/css/ep-dual-button.css',
                'assets/css/ep-dual-button.rtl.css',
                'assets/css/ep-everest-forms.css',
                'assets/css/ep-everest-forms.rtl.css',
                'assets/css/ep-fancy-list.css',
                'assets/css/ep-fancy-list.rtl.css',
                'assets/css/ep-fancy-icons.css',
                'assets/css/ep-fancy-icons.rtl.css',
                'assets/css/ep-featured-box.css',
                'assets/css/ep-featured-box.rtl.css',
                'assets/css/ep-flip-box.css',
                'assets/css/ep-flip-box.rtl.css',
                'assets/css/ep-fluent-forms.css',
                'assets/css/ep-fluent-forms.rtl.css',
                'assets/css/ep-formidable-forms.css',
                'assets/css/ep-formidable-forms.rtl.css',
                'assets/css/ep-image-accordion.css',
                'assets/css/ep-image-accordion.rtl.css',
                'assets/css/ep-image-compare.css',
                'assets/css/ep-image-compare.rtl.css',
                'assets/css/ep-image-stack.css',
                'assets/css/ep-image-stack.rtl.css',
                'assets/css/ep-lightbox.css',
                'assets/css/ep-lightbox.rtl.css',
                'assets/css/ep-logo-grid.css',
                'assets/css/ep-logo-grid.rtl.css',
                'assets/css/ep-member.css',
                'assets/css/ep-member.rtl.css',
                'assets/css/ep-navbar.css',
                'assets/css/ep-navbar.rtl.css',
                'assets/css/ep-open-street-map.css',
                'assets/css/ep-open-street-map.rtl.css',
                'assets/css/ep-panel-slider.css',
                'assets/css/ep-panel-slider.rtl.css',
                'assets/css/ep-price-list.css',
                'assets/css/ep-price-list.rtl.css',
                'assets/css/ep-progress-pie.css',
                'assets/css/ep-progress-pie.rtl.css',
                'assets/css/ep-reading-progress.css',
                'assets/css/ep-reading-progress.rtl.css',
                'assets/css/ep-review-card.css',
                'assets/css/ep-review-card.rtl.css',
                'assets/css/ep-review-card-carousel.css',
                'assets/css/ep-review-card-carousel.rtl.css',
                'assets/css/ep-scroll-button.css',
                'assets/css/ep-scroll-button.rtl.css',
                'assets/css/ep-search.css',
                'assets/css/ep-search.rtl.css',
                'assets/css/ep-slider.css',
                'assets/css/ep-slider.rtl.css',
                'assets/css/ep-static-carousel.css',
                'assets/css/ep-static-carousel.rtl.css',
                'assets/css/ep-static-grid-tab.css',
                'assets/css/ep-static-grid-tab.rtl.css',
                'assets/css/ep-step-flow.css',
                'assets/css/ep-step-flow.rtl.css',
                'assets/css/ep-toggle.css',
                'assets/css/ep-toggle.rtl.css',
                'assets/css/ep-trailer-box.css',
                'assets/css/ep-trailer-box.rtl.css',
                'assets/css/ep-tutor-lms.css',
                'assets/css/ep-tutor-lms.rtl.css',
                'assets/css/ep-twitter-grid.css',
                'assets/css/ep-twitter-grid.rtl.css',
                'assets/css/ep-user-register.css',
                'assets/css/ep-user-register.rtl.css',
                'assets/css/ep-product-grid.css',
                'assets/css/ep-product-grid.rtl.css',
                'assets/css/ep-product-carousel.css',
                'assets/css/ep-product-carousel.rtl.css',
                'assets/css/tippy.css',
                'assets/css/tippy.rtl.css',
                'assets/css/imagezoom.css',
                'assets/css/imagezoom.rtl.css',
                'assets/css/ep-testimonial-grid.css',
                'assets/css/ep-testimonial-grid.rtl.css',
                'assets/css/ep-dark-mode.css',
                'assets/css/ep-dark-mode.rtl.css',
                'assets/css/ep-facebook-feed.css',
                'assets/css/ep-facebook-feed.rtl.css',
                'assets/css/ep-events-calendar-grid.css',
                'assets/css/ep-events-calendar-grid.rtl.css',
                'assets/css/ep-animated-gradient-background.css',
                'assets/css/ep-animated-gradient-background.rtl.css',
                'assets/css/ep-icon-mobile-menu.css',
                'assets/css/ep-icon-mobile-menu.rtl.css',


                //Common JS
                'assets/js/bdt-uikit.js',
                'assets/js/bdt-uikit.min.js',
                // 'assets/js/ep-editor.js',
                // 'assets/js/ep-editor.min.js',
                'assets/js/ep-scripts.js',
                'assets/js/ep-scripts.min.js',
                'assets/js/common/helper.js',
                'assets/js/common/helper.min.js',

                //Widget JS
                'assets/js/modules/ep-accordion.js',
                'assets/js/modules/ep-accordion.min.js',
                'assets/js/modules/ep-background-overlay.js',
                'assets/js/modules/ep-background-overlay.min.js',
                'assets/js/modules/ep-business-hours.js',
                'assets/js/modules/ep-business-hours.min.js',
                'assets/js/modules/ep-contact-form.js',
                'assets/js/modules/ep-contact-form.min.js',
                'assets/js/modules/ep-cookie-consent.js',
                'assets/js/modules/ep-cookie-consent.min.js',
                'assets/js/modules/ep-countdown.js',
                'assets/js/modules/ep-countdown.min.js',
                'assets/js/modules/ep-custom-gallery.js',
                'assets/js/modules/ep-custom-gallery.min.js',
                'assets/js/modules/ep-floating-effects.js',
                'assets/js/modules/ep-floating-effects.min.js',
                'assets/js/modules/ep-flip-box.js',
                'assets/js/modules/ep-flip-box.min.js',
                'assets/js/modules/ep-image-accordion.js',
                'assets/js/modules/ep-image-accordion.min.js',
                'assets/js/modules/ep-image-compare.js',
                'assets/js/modules/ep-image-compare.min.js',
                'assets/js/modules/ep-image-magnifier.js',
                'assets/js/modules/ep-image-magnifier.min.js',
                'assets/js/modules/ep-image-stack.js',
                'assets/js/modules/ep-image-stack.min.js',
                'assets/js/modules/ep-logo-grid.js',
                'assets/js/modules/ep-logo-grid.min.js',
                'assets/js/modules/ep-open-street-map.js',
                'assets/js/modules/ep-open-street-map.min.js',
                'assets/js/modules/ep-panel-slider.js',
                'assets/js/modules/ep-panel-slider.min.js',
                'assets/js/modules/ep-progress-pie.js',
                'assets/js/modules/ep-progress-pie.min.js',
                'assets/js/modules/ep-reading-progress.js',
                'assets/js/modules/ep-reading-progress.min.js',
                'assets/js/modules/ep-reading-timer.js',
                'assets/js/modules/ep-reading-timer.min.js',
                'assets/js/modules/ep-review-card-carousel.js',
                'assets/js/modules/ep-review-card-carousel.min.js',
                'assets/js/modules/ep-scroll-button.js',
                'assets/js/modules/ep-scroll-button.min.js',
                'assets/js/modules/ep-search.js',
                'assets/js/modules/ep-search.min.js',
                'assets/js/modules/ep-slider.js',
                'assets/js/modules/ep-slider.min.js',
                'assets/js/modules/ep-static-carousel.js',
                'assets/js/modules/ep-static-carousel.min.js',
                'assets/js/modules/ep-static-grid-tab.js',
                'assets/js/modules/ep-static-grid-tab.min.js',
                'assets/js/modules/ep-step-flow.js',
                'assets/js/modules/ep-step-flow.min.js',
                'assets/js/modules/ep-toggle.js',
                'assets/js/modules/ep-toggle.min.js',
                'assets/js/modules/ep-tutor-lms-course-grid.js',
                'assets/js/modules/ep-tutor-lms-course-grid.min.js',
                'assets/js/modules/ep-tutor-lms-course-carousel.js',
                'assets/js/modules/ep-tutor-lms-course-carousel.min.js',
                'assets/js/modules/ep-user-register.js',
                'assets/js/modules/ep-user-register.min.js',
                'assets/js/modules/ep-wrapper-link.js',
                'assets/js/modules/ep-wrapper-link.min.js',
                'assets/js/modules/ep-threed-text.js',
                'assets/js/modules/ep-threed-text.min.js',
                'assets/js/modules/ep-product-carousel.js',
                'assets/js/modules/ep-product-carousel.min.js',
                'assets/js/modules/ep-age-gate.js',
                'assets/js/modules/ep-age-gate.min.js',
                'assets/js/modules/ep-dark-mode.js',
                'assets/js/modules/ep-dark-mode.min.js',
                'assets/js/modules/ep-animated-gradient-background.js',
                'assets/js/modules/ep-animated-gradient-background.min.js',
                'assets/js/modules/ep-tooltip.js',
                'assets/js/modules/ep-tooltip.min.js',

                // Vendor JS
                'assets/vendor/js/calendly.min.js',
                'assets/vendor/js/jquery.jclock.min.js',
                'assets/vendor/js/cookieconsent.min.js',
                'assets/vendor/js/image-compare-viewer.min.js',
                'assets/vendor/js/jquery.imagezoom.min.js',
                'assets/vendor/js/tippy.all.min.js',
                'assets/vendor/js/leaflet.min.js',
                'assets/vendor/js/parallax.min.js',
                'assets/vendor/js/popper.min.js',
                'assets/vendor/js/jquery-asPieProgress.min.js',
                'assets/vendor/js/jquery.progressHorizontal.min.js',
                'assets/vendor/js/gridtab.min.js',
                'assets/vendor/js/vanilla-tilt.min.js',
                'assets/vendor/js/anime.min.js',
                'assets/vendor/js/ztext.min.js',
                'assets/vendor/js/chart.min.js',
                'assets/vendor/js/darkmode.min.js',
                'assets/vendor/js/granim.min.js',

                // Controls JS
                'assets/js/controls/**',

                // Widget Files
                // Core
                'modules/accordion/**',
                'modules/animated-link/**',
                'modules/brand-grid/**',
                'modules/business-hours/**',
                'modules/calendly/**',
                'modules/call-out/**',
                'modules/creative-button/**',
                'modules/contact-form/**',
                'modules/cookie-consent/**',
                'modules/countdown/**',
                'modules/custom-gallery/**',
                'modules/dual-button/**',
                'modules/dropbar/**',
                'modules/fancy-list/**',
                'modules/fancy-icons/**',
                'modules/featured-box/**',
                'modules/flip-box/**',
                'modules/image-accordion/**',
                'modules/image-compare/**',
                'modules/image-magnifier/**',
                'modules/image-stack/**',
                'modules/lightbox/**',
                'modules/logo-grid/**',
                'modules/member/**',
                'modules/navbar/**',
                'modules/open-street-map/**',
                'modules/panel-slider/**',
                'modules/price-list/**',
                'modules/progress-pie/**',
                'modules/reading-progress/**',
                'modules/reading-timer/**',
                'modules/review-card/**',
                'modules/review-card-carousel/**',
                'modules/scroll-button/**',
                'modules/search/**',
                'modules/slider/**',
                'modules/static-carousel/**',
                'modules/static-grid-tab/**',
                'modules/step-flow/**',
                'modules/svg-image/**',
                'modules/toggle/**',
                'modules/trailer-box/**',
                'modules/twitter-grid/**',
                'modules/user-register/**',
                'modules/product-grid/**',
                'modules/product-carousel/**',
                'modules/age-gate/**',
                'modules/dark-mode/**',
                'modules/facebook-feed/**',
                'modules/icon-mobile-menu/**',
                //3rd Party
                'modules/caldera-forms/**',
                'modules/contact-form-7/**',
                'modules/everest-forms/**',
                'modules/fluent-forms/**',
                'modules/formidable-forms/**',
                'modules/ninja-forms/**',
                'modules/tutor-lms-course-carousel/**',
                'modules/tutor-lms-course-grid/**',
                'modules/we-forms/**',
                'modules/testimonial-grid/**',
                'modules/events-calendar-grid/**',
                //extensions
                'modules/backdrop-filter/**',
                'modules/background-overlay/**',
                'modules/equal-height/**',
                'modules/floating-effects/**',
                'modules/threed-text/**',
                'modules/wrapper-link/**',
                'modules/grid-line/**',
                'modules/animated-gradient-background/**',
                'modules/tooltip/**',
                'modules/transform-effects/**',
                'modules/custom-js/**',


                ], dest: 'node_modules/bdthemes-element-pack-lite/', filter: 'isFile'},

              // includes files within path and its sub-directories
              //{expand: true, src: ['path/**'], dest: 'dest/'},

              // makes all src relative to cwd
              //{expand: true, cwd: 'assets/css/ep-accordion.css', src: ['**'], dest: 'node_modules/bdthemes-element-pack-lite/'},

              // flattens results to a single level
              //{expand: true, flatten: true, src: ['path/**'], dest: 'dest/', filter: 'isFile'},
            ],
          },
        },


        buildnumber: {
            options: {
              field: 'buildnum',
            },
            files: ['package.json']
        },

    });

    grunt.loadNpmTasks('grunt-rtlcss');
    grunt.loadNpmTasks('grunt-contrib-concat');
    grunt.loadNpmTasks('grunt-terser');
    grunt.loadNpmTasks('grunt-contrib-copy');
    grunt.loadNpmTasks('grunt-build-number');

    grunt.registerTask('default', ['less', 'rtlcss', 'concat', 'terser', 'copy', 'buildnumber', 'watch']);
};